language: ruby
cache:
  - bundler
  - yarn
rvm:
  - 2.4.1

env:
  - DB_USERNAME=postgres DB_DATABASE=timetable_ci DB_HOST=localhost DB_PASSWORD=''

sudo: required
addons:
  postgresql: "9.6"
  chrome: stable

script:
  - bundle exec rake 
  - yarn lint

before_install:
  - nvm install v11.4.0

before_script:
  - yarn install
  - bundle exec rake db:create
  - cp .env.example .env
