language: ruby
cache:
  - bundler
  - yarn
rvm:
  - 2.7.0

env:
  - DB_USERNAME=postgres DB_DATABASE=timetable_ci DB_HOST=localhost DB_PASSWORD=''

sudo: required
addons:
  postgresql: "9.6"
  chrome: stable

script:
  - bundle exec rake
  - yarn lint

before_install:
  - gem install bundler:2.1.4
  - nvm install v13.9.0

before_script:
  - yarn install
  - bundle exec rake db:create
  - cp .env.example .env
