global: &global
  adapter: postgresql
  min_messages: warning
  encoding: utf8
  database: <%= ENV['DB_DATABASE'] %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: "<%= ENV['DB_PASSWORD'] %>"

development:
  <<: *global

staging:
  <<: *global

production:
  <<: *global

test:
  <<: *global
  database: timetable_test
